[package]
name = "winspell"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.93"

[dependencies.windows]
version = "0.58"
features = [
    "Win32_System_Com",
    "Win32_Foundation",
    "Win32_Globalization",
    "Win32_System_Threading",
]
